"""EUR-Lex RSS poller — emits a Markdown digest of regulation-keyword hits.

Stdlib only. Python 3.10+.

Usage:
    python tools/eur_lex_rss.py [--out-dir /tmp] [--feed-url URL]

Notes:
- The official EUR-Lex RSS endpoint historically lives under
  https://eur-lex.europa.eu/EN/legal-content/RSS/recent-legal-content.xml
  Coverage of that exact URL has shifted between EUR-Lex redesigns; the
  --feed-url flag lets the operator override.
- We use xml.etree.ElementTree (stdlib) to parse RSS 2.0.
- Filter matches the same regulation keyword list as auto_update.py.
"""
from __future__ import annotations

import argparse
import datetime as _dt
import os
import sys
import urllib.error
import urllib.request
import xml.etree.ElementTree as ET

DEFAULT_FEED_URL = "https://eur-lex.europa.eu/EN/legal-content/RSS/recent-legal-content.xml"
USER_AGENT = "awesome-eu-compliance-tooling-bot/0.1 (+EUR-Lex digest)"

EU_KEYWORDS: list[str] = [
    "GDPR", "EHDS", "CRA", "AI Act", "NIS2", "DORA",
    "MDR", "IVDR", "DPIA", "compliance", "ENISA", "EUR-Lex",
]


def fetch_feed(url: str, timeout: float = 15.0) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            return resp.read()
    except (urllib.error.URLError, urllib.error.HTTPError, TimeoutError, OSError) as e:
        sys.stderr.write(f"[eur_lex_rss] fetch failed: {e}\n")
        return b""


def parse_items(xml_bytes: bytes) -> list[dict]:
    if not xml_bytes:
        return []
    try:
        root = ET.fromstring(xml_bytes)
    except ET.ParseError as e:
        sys.stderr.write(f"[eur_lex_rss] parse failed: {e}\n")
        return []

    items: list[dict] = []
    # RSS 2.0: <rss><channel><item>...</item></channel></rss>
    # Atom alt: <feed><entry>... — try both.
    for item in root.iter("item"):
        items.append({
            "title": (item.findtext("title") or "").strip(),
            "link": (item.findtext("link") or "").strip(),
            "description": (item.findtext("description") or "").strip(),
            "pub_date": (item.findtext("pubDate") or "").strip(),
        })
    if not items:
        # Atom fallback
        ns = {"atom": "http://www.w3.org/2005/Atom"}
        for entry in root.iter("{http://www.w3.org/2005/Atom}entry"):
            title_el = entry.find("atom:title", ns)
            summary_el = entry.find("atom:summary", ns)
            link_el = entry.find("atom:link", ns)
            updated_el = entry.find("atom:updated", ns)
            items.append({
                "title": (title_el.text or "").strip() if title_el is not None and title_el.text else "",
                "link": (link_el.attrib.get("href", "") if link_el is not None else ""),
                "description": (summary_el.text or "").strip() if summary_el is not None and summary_el.text else "",
                "pub_date": (updated_el.text or "").strip() if updated_el is not None and updated_el.text else "",
            })
    return items


def filter_by_keywords(items: list[dict], keywords: list[str]) -> list[dict]:
    kws = [k.lower() for k in keywords]
    out: list[dict] = []
    for it in items:
        hay = (it.get("title", "") + " " + it.get("description", "")).lower()
        if any(k in hay for k in kws):
            out.append(it)
    return out


def emit_digest(items: list[dict], today: _dt.date) -> str:
    lines: list[str] = []
    lines.append(f"# EUR-Lex digest — {today.isoformat()}")
    lines.append("")
    lines.append(f"Generated by `tools/eur_lex_rss.py`. Filter: {', '.join(EU_KEYWORDS)}.")
    lines.append("")
    if not items:
        lines.append("_No matching items in this poll._")
        return "\n".join(lines) + "\n"
    lines.append("| Title | Date | Link |")
    lines.append("|-------|------|------|")
    for it in items:
        title = it.get("title", "").replace("|", "\\|")
        date = it.get("pub_date", "")
        link = it.get("link", "")
        lines.append(f"| {title} | {date} | {link} |")
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--feed-url", default=DEFAULT_FEED_URL)
    p.add_argument("--out-dir", default="/tmp", help="output directory for the Markdown digest")
    p.add_argument("--dry-run", action="store_true", help="print to stdout instead of writing a file")
    args = p.parse_args(argv)

    today = _dt.date.today()
    xml_bytes = fetch_feed(args.feed_url)
    items = parse_items(xml_bytes)
    matched = filter_by_keywords(items, EU_KEYWORDS)
    digest = emit_digest(matched, today)

    if args.dry_run:
        sys.stdout.write(digest)
        return 0

    out_path = os.path.join(args.out_dir, f"eur_lex_digest_{today.isoformat()}.md")
    try:
        os.makedirs(args.out_dir, exist_ok=True)
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(digest)
    except OSError as e:
        sys.stderr.write(f"[eur_lex_rss] write failed: {e}\n")
        return 1
    sys.stdout.write(f"wrote {out_path} ({len(matched)} items)\n")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
